# Raspberry Pi CMake toolchain
set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR arm)

set(CMAKE_CXX_COMPILER TODO ARM 32 bit cross-compiler)

# set(CMAKE_SYSROOT /path/to/raspberrypi/sysroot)
# set(CMAKE_FIND_ROOT_PATH  ${CMAKE_SYSROOT})
# set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
# set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
# set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
